# This is an example goreleaser.yaml file with some sane defaults.
project_name: nausys
build:
  skip: true
changelog:
  sort: desc
  filters:
    exclude:
      - docs
      - changelog
      - readme
      - ^Merge pull request
