name: Linting with golangci-lint
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "*.yml"
      - "Makefile"
      - "docs/*.md"
      - ".gitignore"
      - "LICENSE"
      - ".github/*.yml"
      - ".github/ISSUE_TEMPLATE/*.md"
      - ".github/*.md"
      - ".github/workflows/main.yml"
      - ".github/workflows/release.yml"
  pull_request:
    paths-ignore:
      - "**.md"
      - "*.yml"
      - "Makefile"
      - "docs/*.md"
      - ".gitignore"
      - "LICENSE"
      - ".github/*.yml"
      - ".github/ISSUE_TEMPLATE/*.md"
      - ".github/*.md"
      - ".github/workflows/main.yml"
      - ".github/workflows/release.yml"
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.17.x]
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: golangci-lint
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: --issues-exit-code=0 --new=true --sort-results --skip-dirs-use-default --tests=false
